- app/models/nap_space.rb
- db/migrate/20221126044014_create_nap_spaces.rb
- db/schema.rb
- test/models/nap_space_test.rb
added nap_space table, please review c:
> added nap_space table

- app/controllers/nap_spaces_controller.rb
- test/controllers/nap_spaces_controller_test.rb
created the nap_spaces controller, ready for crud actions!
> created nap_spaces controller

- app/controllers/nap_spaces_controller.rb
- app/views/nap_spaces/home.html.erb
- config/routes.rb
I have added nap_spaces home routes & method in controller & view page.
> nap_space-home

- app/controllers/nap_spaces_controller.rb
- app/views/nap_spaces/index.html.erb
- config/routes.rb
I have just added index in routes, nap_space controller and view/index.html.erb.
Thanks
> index for nap-space

- db/migrate/20221129101700_add_image_url_to_nap_space.rb
- db/schema.rb
added image_url column to nap_space table as a string - will update datatype to file once we integrate w cloudinary
> added image url column to nap_space model

- app/controllers/nap_spaces_controller.rb
- app/views/nap_spaces/_form.html.erb
- app/views/nap_spaces/_nap_space.html.erb
- app/views/nap_spaces/edit.html.erb
- app/views/nap_spaces/home.html.erb
- app/views/nap_spaces/index.html.erb
- app/views/nap_spaces/new.html.erb
- app/views/nap_spaces/show.html.erb
- config/routes.rb
just created update and edit and created form for new and edit. created view files and made links for testing. Thanks
> Nap space edit update

- app/controllers/nap_spaces_controller.rb
redirect destination may need changing?
> User can delete napspace

- app/controllers/bookings_controller.rb
- app/controllers/nap_spaces_controller.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/nap_spaces/show.html.erb
- config/routes.rb
just did show and index in routes, controller, and view.
> index,show

- app/controllers/bookings_controller.rb
- app/models/booking.rb
back end to accept/decline/cancel bookings as appropriate users
> User can accept/decline/cancel booking

- app/assets/stylesheets/scss/custom/structure/_general.scss
- app/assets/stylesheets/scss/custom/structure/_topbar.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar2.html.erb
updated navbar links - signup , home, all napspaces
> Archie navbar signup

- app/models/booking.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
booking total_cost instance method implemented, returns cost of booking
added to bookings#index and bookings#show views
> booking-cost

- app/models/booking.rb
- app/models/review.rb
- db/migrate/20221203030453_create_reviews.rb
- db/schema.rb
- test/models/review_test.rb
just did review model, relation, validation, and migration. please have a look cheers.
> review model

- app/controllers/bookings_controller.rb
- app/controllers/nap_spaces_controller.rb
- app/controllers/reviews_controller.rb
- app/models/nap_space.rb
- app/views/bookings/index.html.erb
- app/views/nap_spaces/show.html.erb
- app/views/reviews/_form.html.erb
- config/routes.rb
- test/controllers/reviews_controller_test.rb
user can create review and will show for each nap_space with user_name. Please have a look at all. Thanks
> created review & show with bookings

- app/assets/stylesheets/application.scss
- app/javascript/controllers/flatpickr_controller.js
- app/javascript/controllers/index.js
- app/models/booking.rb
- app/views/bookings/_form.html.erb
- package.json
- yarn.lock
New booking form now uses flatpickr for datetimes
> Booking flatpickr

- app/models/booking.rb
- app/views/bookings/index.html.erb
bookings in index now display time in mins or hrs based on whether or not the booking is less than a hr long
> booking duration will now display in hrs when >59 mins long

- app/models/booking.rb
> updated method name from cancelled to cancelled?

- app/assets/stylesheets/application.scss
- updated stylesheet import 
- from: `@import "flatpickr/dist/flatpickr.css"`
- to: `@import "flatpickr/dist/flatpickr"`
> fixed flatpickr rending bug

- config/environments/production.rb
> productin time

- app/assets/stylesheets/scss/custom/components/_accordion.scss
- app/views/bookings/index.html.erb
- app/views/nap_spaces/index.html.erb
> Bookings page accordian

- app/controllers/nap_spaces_controller.rb
- app/views/nap_spaces/index_by_user.html.erb
- app/views/shared/_navbar2.html.erb
- config/routes.rb
can someone please take a looky
> Add user nap space index

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
> Bug fix - past bookings displaying in upcoming naps

- app/views/shared/_navbar2.html.erb
> puting gap

- app/views/bookings/index.html.erb
> linked nap_space description on bookings index to nap_space show

- app/views/nap_spaces/show.html.erb
> adding_yeahhhhhhhhhhhhh

- app/views/shared/_navbar2.html.erb
- updated from "find a nap space" to "i need a nap"
> small copy change in nav bar

- app/javascript/application.js
- app/models/user.rb
- app/views/shared/_navbar2.html.erb
Idea: user receives a notification when they have upcoming host bookings that require approval/dismissal 
- tried to implement this using bootstrap toasts but wasn't able to get them to work 😕 
- added a badge to the bookings link in nav bar displaying no. of bookings to approve as a way to keep myself happy while I figure out toasts 😆 
https://user-images.githubusercontent.com/68765634/219053389-fe715f8c-c7cc-4d1f-8781-dbc6e5554fad.mov
> Requested bookings notifications

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar2.html.erb
- db/migrate/20230221081655_update_default_name_users.rb
- db/schema.rb
- removed unused fields from signup form
- updated signup icon to be different to login
- updated default value of user name to be less gendered
- updated copy from 'exit' to 'log out' when ending user session
Before:
After:
> Sign up update
